pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '--rm -v /root/.m2:/root/.m2 --name=config-service --hostname=127.0.0.1 --net=host'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Run') {
            when {
                branch 'master'
            }
            steps {
                sh 'java -jar target/*.jar >> nohup.out &'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
            }
        }
    }
}